[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.15.0"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"
0g-agent-nft = { version = "1.0.0", git = "https://github.com/0gfoundation/0g-agent-nft.git", rev = "b86e108a49bf3601bf57f1f0b3166dce2cb15928" }

[rpc_endpoints]
zero-gravity-testnet = "${RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
